# Generated by Django 5.2.7 on 2025-10-19 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(max_length=50)),
                ('is_disable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id_evaluacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_evaluacion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Evaluación',
                'verbose_name_plural': 'Tipos de Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesores', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_profesor', models.CharField(max_length=60)),
                ('is_disable', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='HorarioExamen',
            fields=[
                ('id_horario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_examen', models.DateField()),
                ('hora_examen', models.TimeField()),
                ('aula', models.ForeignKey(db_column='id_aula', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apexunsisapi.aula')),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='apexunsisapi.grupo')),
                ('materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.PROTECT, to='apexunsisapi.materia')),
                ('periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.PROTECT, to='apexunsisapi.periodo')),
                ('profesor', models.ForeignKey(db_column='id_profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_como_principal', to='apexunsisapi.profesor')),
                ('profesor_sinodal', models.ForeignKey(blank=True, db_column='id_profesor_sinodal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_como_sinodal', to='apexunsisapi.profesor')),
                ('evaluacion', models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.PROTECT, to='apexunsisapi.tipoevaluacion')),
            ],
            options={
                'verbose_name': 'Horario de Examen',
                'verbose_name_plural': 'Horarios de Exámenes',
                'constraints': [models.UniqueConstraint(fields=('periodo', 'evaluacion', 'grupo', 'materia'), name='horario_unico_por_materia_grupo')],
            },
        ),
    ]
