# Generated by Django 5.2.7 on 2025-10-19 03:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apexunsisapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aula',
            new_name='Aulas',
        ),
        migrations.RenameModel(
            old_name='Grupo',
            new_name='Grupos',
        ),
        migrations.RenameModel(
            old_name='Materia',
            new_name='Materias',
        ),
        migrations.RenameModel(
            old_name='Periodo',
            new_name='Periodos',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
        migrations.RenameField(
            model_name='profesores',
            old_name='id_profesores',
            new_name='id_profesor',
        ),
    ]
